### ISSUE TITLE
Expand TextLabels

### ISSUE THREAD

**Issue by S0P4** [altmp/altv-issues#1964]
### Description of the problem

Current text labels are okay, but i will be nicer if they got extended.

### Desired solution for the problem

Text center for Text Label could it be configurable. And add the support for in line color change using GTA V text modifiers:

`~r~` = Red
`~b~` = Blue
`~g~` = Green
`~y~` = Yellow
`~p~` = Purple
`~q~` = Pink
`~o~` = Orange
`~c~` = Grey
`~m~` = Darker Grey
`~u~` = Black
`~n~` = New Line (This will be an extra because \n works for jumping the line)
`~s~` = Default White
`~w~` = White
`~h~` = Bold Text

Or an alternative way using css.

### Version

rc/15.0-rc4
```[tasklist]
### Tasks
- [x] Separate text rendering
- [x] Color via tags
- [x] Alignment as argument
- [x] Font via tags
- [x] Icon loading support
- [x] Optimization
```

**Comment by xxshady** [comment]
if you meant `~r~`, try:
```
`~r~`
```

**Comment by zziger** [comment]
```[tasklist]
### Tasks
- [ ] Separate text rendering
- [ ] Colored glyphs support (emojis, icons etc)
- [ ] Color via tags
- [ ] Outline via tags
- [ ] Alignment via tags
- [ ] Font via tags
- [ ] Texture via tags (optional)
- [ ] Update method (optional)
```

**Comment by zziger** [comment]
It was decided to use XML-like formatting tags instead of GTA color codes to support more formatting features and inline images. Feature is being QA-tested now and will be most likely merged to `dev` branch soon.

![image](https://github.com/altmp/altv-issues/assets/27638710/0ca172e2-2f19-4936-a494-099f3f6f6992)

**Comment by ThomasMarangoni** [comment]
Added in latest dev
