### ISSUE TITLE
Some serverside vehicle setters not wokring correctly

### ISSUE THREAD

**Issue by C0kkie** [altmp/altv-issues#737]
**Client/server version**

`Build #dev/2.1-dev65, branch dev`

**Current behavior**

- [ ] setWindowOpened - true works perfectly, false isnt synced, only if you restream it (like dim change for example). If the driver leaves the vehicle, the window will be open again for the user who did a dim change befor

- [ ] setWindowDamaged - doesnt work at all, also not on restream
- [ ] setWheelOnFire - works with true, but you cant delete the fire if you seat the state to false
- [ ] setWheelHealth - doesnt fix the vehicle health visually, but i am not sure if it should
- [ ] setWheelHasTire - false works as it should, but true has to be restreamed
- [ ] setWheelDetached - works if you are in range, if you restream they are attached again, false isnt working if you are in range
- [ ] setSpecialLightDamaged - works in range, if you restream they are fixed again
- [ ] setPartDamageLevel - not working
- [ ] setPartBulletHoles - working in range for non net owner | if you restream its resettet 
- [ ] setLightDamaged - working in range | on restream its resettet (if more then 1 are damaged) | isDamaged false doesnt work if it was damaged
- [ ] setDoorState - works in range, except the for the net owner, if you restream it takes 1 second to get the correct state
- [ ] setBumperDamageLevel - doesnt work at all
- [ ] setArmoredWindowShootCount - doesnt work
- [ ] setArmoredWindowHealth - doesnt work
- [ ] petrolTankHealth setter truncating most-significant bits ( https://github.com/altmp/altv-issues/issues/579)
- [ ] Vehicle.dirtLevel property always return 0 or 41 and setter problem (https://github.com/altmp/altv-issues/issues/372)
- [ ] Native setVehicleNitroEnabled not working as it used to (https://github.com/altmp/altv-issues/issues/604)
- [ ] Make slipstream settable per vehicle, fix visuals, make boost customizable (https://github.com/altmp/altv-issues/issues/599)

- [ ] Native setVehicleLights is not synced
- [ ] Sync setVehicleIndicatorLights native function
- [ ] Sync setVehicleSearchlight native function https://github.com/altmp/altv-issues/issues/337
- [ ] Sync setVehicleHasMutedSirens native function
- [ ] Vehicle.EngineOn & ManualEngineControl getter/setter sync issue
- [ ] Ability to change vehicle rpm
- [ ] Add vehicle bulletproof tyres property (https://github.com/altmp/altv-issues/issues/600)

Also if you shoot a window like this: https://img.c0kkie.de/c0kkie_08-12-2020_23-52-49.jpg
And you restream the window is totally broken https://img.c0kkie.de/c0kkie_08-12-2020_23-53-02.jpg

**Comment by martonp96** [comment]
use emitClient

**Comment by FDiskas** [comment]
Please also check **getDoorState** method
`vehicle.getDoorState(doorIndex);` always returns 0
```
[17:48:44] {"doorIndex":5,"doorState":0}
[17:49:51] {"doorIndex":2,"doorState":0}
[17:50:23] {"doorIndex":1,"doorState":0}
```

![image](https://user-images.githubusercontent.com/468006/103154862-61252e00-47a3-11eb-8e37-1ea6e0d7bdec.png)

**Comment by FDiskas** [comment]
Also there is more getters not working
- [ ] handbrakeActive
- [ ] lockState
- [ ] engineOn
- [ ] getDoorState

**Comment by Kingwolfi** [comment]
I did some tests and the vehicle.SetDoorState only works for no netowner players but not for the netowner (RPC Error). The other result is if a door is open and the netowner walks away and stream back in the vehicle the door is closed. If another player is in range of the vehicle the netowner is changed to this one and the doors are open if you stream in the vehicle. there is something wrong with the netowner handling. 

If you use this code the doorstate changes also for the netowner but afterwards the sync is bad (just a test)
vehicle.SetNetworkOwner(null);
vehicle.SetDoorState(door, state);

**Comment by FabianTerhorst** [comment]
Test the wheel setters again in 11.0-dev21

**Comment by nacelol** [comment]
> getDoorState does seem to work fine for doors, but bonnet and trunk (door id 4 and 5) still always return 0 for some vehicles, namely `rebel`, `rebel2`, `bodhi2`, probably some others with similar trunks/bonnets.

Yeah, still relevant today. This seems to be the problem in all vehicles that have only 2 seats (e.g. sultanrs, winky)
